import React from "react";
import Image from "next/image";
import Link from "next/link";
import { Metadata } from "next";
import TechnicalAnnotation from "@/components/ui/TechnicalAnnotation";
import StoryNavigation from "@/components/story/StoryNavigation";
import ChapterTransition from "@/components/story/ChapterTransition";
import VisualWorldSection from "@/components/story/VisualWorldSection";
import { ALKOTA_STORY_MEDIA } from "@/content/media/alkotaStoryMedia";
import { ArrowRight, Compass, Flag, Users } from "lucide-react";

export const metadata: Metadata = {
  title: "Our Story | Pete Currey & Cycling History",
  description: "Explore the riding history, paddock culture, and engineering journey behind founder Pete Currey and the creation of ALKOTA Performance Engineering.",
  openGraph: {
    title: "Our Story | Pete Currey & Cycling History",
    description: "Explore the riding history, paddock culture, and engineering journey behind founder Pete Currey and the creation of ALKOTA Performance Engineering.",
    images: [ALKOTA_STORY_MEDIA.peteRidingHistory.src],
  },
};

export default function OurStoryPage() {
  return (
    <div className="w-full bg-alkota-carbon text-alkota-white pt-24 min-h-screen space-y-0">
      <StoryNavigation />

      {/* Hero Header */}
      <VisualWorldSection world="ALPINE_PRECISION" id="story-hero">
        <div className="space-y-8">
          <div className="space-y-4">
            <TechnicalAnnotation label="CHAPTER 02" value="OUR STORY" variant="slate" />
            <h1 className="font-display font-medium text-5xl sm:text-7xl lg:text-8xl uppercase tracking-tight text-alkota-black leading-[0.9]">
              DECADES ON TERRAIN.<br />
              <span className="text-alkota-graphite">ONE DIRECTION.</span>
            </h1>
            <p className="font-mono text-xs text-alkota-graphite uppercase tracking-wider font-semibold">
              PETE CURREY • RIDING HISTORY • PADDOCK CULTURE
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center pt-4">
            <div className="lg:col-span-6 space-y-6 font-sans">
              <p className="text-xl sm:text-2xl text-alkota-black font-light leading-snug">
                ALKOTA was not conceived in a corporate board room or generated by market analysis. It grew out of decades spent riding mountain trails, racing downhill paddocks, and obsessing over how bicycles behave under pressure.
              </p>

              <div className="space-y-4 text-sm text-alkota-slate leading-relaxed font-light">
                <p>
                  Pete Currey’s relationship with mountain biking began long before computer-aided design and carbon monocoque layups dominated the sport. Through years of racing, mechanics, and product testing, one constant remained obvious: most bicycles were compromises built from catalog parts.
                </p>
                <p>
                  Rather than accepting those compromises, Pete set out to reverse-engineer the complete riding experience—evaluating every link, damper, bearing, and fiber vector to create one perfect machine.
                </p>
              </div>
            </div>

            <div className="lg:col-span-6 space-y-3">
              <div className="relative w-full h-[420px] sm:h-[500px] bg-alkota-snow border border-black/10 overflow-hidden shadow-2xl">
                <Image
                  src={ALKOTA_STORY_MEDIA.peteRidingHistory.src}
                  alt={ALKOTA_STORY_MEDIA.peteRidingHistory.alt}
                  fill
                  priority
                  sizes="(max-width: 1024px) 100vw, 50vw"
                  className="object-cover object-center"
                />
              </div>
              <div className="font-mono text-[10px] text-alkota-slate flex items-center justify-between uppercase">
                <span>FOUNDER RIDING HISTORY</span>
                <span>ORIGIN ARCHIVE</span>
              </div>
            </div>
          </div>
        </div>
      </VisualWorldSection>

      {/* Paddock & Event Environment — WORLD 03 TERRAIN & HUMAN */}
      <VisualWorldSection world="TERRAIN_HUMAN" id="paddock-culture">
        <div className="space-y-12">
          <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 border-b border-white/10 pb-8">
            <div className="space-y-3">
              <TechnicalAnnotation label="PADDOCK & FIELD DIALOGUE" value="RACE CULTURE" variant="signal" />
              <h2 className="font-display font-medium text-4xl sm:text-6xl uppercase tracking-tight text-alkota-white leading-[0.9]">
                LEARNING FROM<br />
                <span className="text-alkota-slate">THE PADDOCK.</span>
              </h2>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="space-y-4">
              <div className="relative w-full h-[360px] bg-alkota-carbon border border-white/10 overflow-hidden shadow-2xl">
                <Image
                  src={ALKOTA_STORY_MEDIA.paddockEnvironment.src}
                  alt={ALKOTA_STORY_MEDIA.paddockEnvironment.alt}
                  fill
                  sizes="(max-width: 768px) 100vw, 50vw"
                  className="object-cover object-center"
                />
              </div>
              <h3 className="font-display text-xl font-bold uppercase text-alkota-white">
                PADDOCK PRESENCE
              </h3>
              <p className="font-sans text-xs text-alkota-snow/80 leading-relaxed font-light">
                Event paddocks and race pits are the ultimate feedback loop. Direct dialogue with riders after high-velocity runs cuts through marketing claims and reveals true hardware performance.
              </p>
            </div>

            <div className="space-y-4">
              <div className="relative w-full h-[360px] bg-alkota-carbon border border-white/10 overflow-hidden shadow-2xl">
                <Image
                  src={ALKOTA_STORY_MEDIA.founderRiderDialogue.src}
                  alt={ALKOTA_STORY_MEDIA.founderRiderDialogue.alt}
                  fill
                  sizes="(max-width: 768px) 100vw, 50vw"
                  className="object-cover object-center"
                />
              </div>
              <h3 className="font-display text-xl font-bold uppercase text-alkota-white">
                RIDER DE-BRIEF SESSIONS
              </h3>
              <p className="font-sans text-xs text-alkota-snow/80 leading-relaxed font-light">
                Reviewing shock stroke telemetry and chassis compliance notes immediately after trail runs ensures engineering targets align with physical rider sensation.
              </p>
            </div>
          </div>
        </div>
      </VisualWorldSection>

      {/* Design Meetings — WORLD 02 ENGINEERING LAB */}
      <VisualWorldSection world="ENGINEERING_LAB" id="design-meetings">
        <div className="space-y-12">
          <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 border-b border-white/10 pb-8">
            <div className="space-y-3">
              <TechnicalAnnotation label="DEVELOPMENT DIALOGUE" value="DESIGN MEETINGS" variant="signal" />
              <h2 className="font-display font-medium text-4xl sm:text-6xl uppercase tracking-tight text-alkota-white leading-[0.9]">
                ENGINEERING<br />
                <span className="text-alkota-slate">DISCIPLINE.</span>
              </h2>
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
            <div className="lg:col-span-7 relative w-full h-[400px] sm:h-[480px] bg-alkota-black border border-white/10 overflow-hidden shadow-2xl">
              <Image
                src={ALKOTA_STORY_MEDIA.engineeringDesignMeeting.src}
                alt={ALKOTA_STORY_MEDIA.engineeringDesignMeeting.alt}
                fill
                sizes="(max-width: 1024px) 100vw, 60vw"
                className="object-cover object-center"
              />
            </div>

            <div className="lg:col-span-5 space-y-6 font-sans">
              <p className="text-lg text-alkota-white font-light leading-relaxed">
                Design meetings at ALKOTA are governed by data, telemetry graphs, and CAD cross-sections rather than styling trends.
              </p>
              <p className="text-xs text-alkota-slate font-light leading-relaxed">
                Every pivot location, leverage curve, and carbon wall thickness is scrutinized until it satisfies our strict baseline performance criteria.
              </p>

              <div className="pt-4">
                <Link
                  href="/about/reverse-engineering"
                  className="inline-flex items-center gap-2 px-6 py-3 bg-alkota-signal text-alkota-black font-mono text-xs font-bold uppercase hover:bg-white transition-colors"
                >
                  <span>NEXT: REVERSE ENGINEERING</span>
                  <ArrowRight className="w-4 h-4" />
                </Link>
              </div>
            </div>
          </div>
        </div>
      </VisualWorldSection>

      <ChapterTransition currentSlug="story" />
    </div>
  );
}
