/**
 * ALKOTA Performance Engineering — Central Story Media Manifest
 * 
 * Single source of truth tracking all visual storytelling photography,
 * subject metadata, visual world tags, focal points, and accessibility captions.
 */

export type StoryMediaCategory =
  | "founder"
  | "origin"
  | "retail"
  | "racing"
  | "industry"
  | "design"
  | "engineering"
  | "carbon"
  | "component"
  | "workshop"
  | "event"
  | "testing"
  | "product"
  | "alpine";

export type VisualWorld = "ALPINE_PRECISION" | "ENGINEERING_LAB" | "TERRAIN_HUMAN";

export interface StoryMediaAsset {
  id: string;
  src: string;
  category: StoryMediaCategory;
  subjects: string[];
  bikeFinish?: "GLACIER" | "CARBON" | "PROTOTYPE" | "NONE";
  orientation: "landscape" | "portrait" | "square";
  environment: VisualWorld;
  priority: number;
  focalPoint?: string;
  alt: string;
  caption?: string;
}

export const ALKOTA_STORY_MEDIA: Record<string, StoryMediaAsset> = {
  peteFounderPortrait: {
    id: "pete-founder-portrait",
    src: "/images/story/pete-currey-founder-portrait.png",
    category: "founder",
    subjects: ["Pete Currey", "Founder"],
    bikeFinish: "NONE",
    orientation: "portrait",
    environment: "ALPINE_PRECISION",
    priority: 1,
    focalPoint: "center 20%",
    alt: "Pete Currey, founder of ALKOTA Performance Engineering, in alpine environment",
    caption: "Pete Currey — Founder & Principal Engineer, ALKOTA Performance Engineering",
  },
  peteWorkshopLab: {
    id: "pete-workshop-lab",
    src: "/images/story/pete-currey-workshop-laboratory.png",
    category: "workshop",
    subjects: ["Pete Currey", "Workshop", "CAD"],
    bikeFinish: "CARBON",
    orientation: "landscape",
    environment: "ENGINEERING_LAB",
    priority: 1,
    focalPoint: "center center",
    alt: "Pete Currey in the ALKOTA engineering development workshop with Project 01 chassis",
    caption: "Analyzing chassis compliance vectors in the development lab",
  },
  peteGlacierWhite: {
    id: "pete-glacier-white",
    src: "/images/story/pete-currey-glacier-white-presentation.png",
    category: "founder",
    subjects: ["Pete Currey", "Project 01", "Glacier White"],
    bikeFinish: "GLACIER",
    orientation: "landscape",
    environment: "ALPINE_PRECISION",
    priority: 1,
    focalPoint: "center center",
    alt: "Pete Currey presenting Project 01 in Glacier White finish",
    caption: "Project 01 Glacier White baseline presentation",
  },
  peteNakedCarbon: {
    id: "pete-naked-carbon",
    src: "/images/story/pete-currey-naked-carbon-inspection.png",
    category: "founder",
    subjects: ["Pete Currey", "Project 01", "Naked Carbon"],
    bikeFinish: "CARBON",
    orientation: "landscape",
    environment: "ENGINEERING_LAB",
    priority: 1,
    focalPoint: "center center",
    alt: "Pete Currey inspecting Project 01 Naked Carbon composite layup",
    caption: "Inspecting 3K carbon weave layup transition zones",
  },
  peteAlpineArchitectural: {
    id: "pete-alpine-architectural",
    src: "/images/story/pete-currey-alpine-architectural.png",
    category: "alpine",
    subjects: ["Pete Currey", "Alpine"],
    bikeFinish: "NONE",
    orientation: "landscape",
    environment: "ALPINE_PRECISION",
    priority: 2,
    alt: "Pete Currey against alpine mountain architecture",
    caption: "Alpine environments shape our engineering standards",
  },
  peteRidingHistory: {
    id: "pete-riding-history",
    src: "/images/story/pete-currey-riding-history-origin.png",
    category: "origin",
    subjects: ["Pete Currey", "Riding History"],
    bikeFinish: "NONE",
    orientation: "landscape",
    environment: "TERRAIN_HUMAN",
    priority: 1,
    alt: "Pete Currey riding early downhill trails",
    caption: "Decades of mountain bike riding and racing history",
  },
  paddockEnvironment: {
    id: "paddock-environment",
    src: "/images/story/mountain-event-paddock-environment.png",
    category: "event",
    subjects: ["Paddock", "Races", "Culture"],
    bikeFinish: "NONE",
    orientation: "landscape",
    environment: "TERRAIN_HUMAN",
    priority: 2,
    alt: "ALKOTA paddock environment at alpine mountain event",
    caption: "Paddock presence — learning directly from rider feedback",
  },
  tradeShowPresentation: {
    id: "trade-show-presentation",
    src: "/images/story/trade-show-paddock-presentation.png",
    category: "industry",
    subjects: ["Trade Show", "Industry"],
    bikeFinish: "GLACIER",
    orientation: "landscape",
    environment: "ALPINE_PRECISION",
    priority: 2,
    alt: "ALKOTA technical presentation at international cycling event",
    caption: "Technical dialogue with industry engineers",
  },
  founderRiderDialogue: {
    id: "founder-rider-dialogue",
    src: "/images/story/founder-rider-dialogue-session.png",
    category: "racing",
    subjects: ["Pete Currey", "Rider Dialogue", "Feedback"],
    bikeFinish: "PROTOTYPE",
    orientation: "landscape",
    environment: "TERRAIN_HUMAN",
    priority: 1,
    alt: "Pete Currey discussing trail telemetry feedback with rider",
    caption: "De-briefing telemetry data after high-speed trail runs",
  },
  engineeringDesignMeeting: {
    id: "engineering-design-meeting",
    src: "/images/story/engineering-design-meeting.png",
    category: "design",
    subjects: ["Design Meeting", "CAD", "Kinematics"],
    bikeFinish: "NONE",
    orientation: "landscape",
    environment: "ENGINEERING_LAB",
    priority: 1,
    alt: "ALKOTA engineering team reviewing kinematic suspension curves",
    caption: "Reviewing leverage ratio progression and anti-squat curves",
  },
  chassisEngineeringReview: {
    id: "chassis-engineering-review",
    src: "/images/story/chassis-engineering-review.png",
    category: "engineering",
    subjects: ["Chassis", "Engineering", "CAD"],
    bikeFinish: "CARBON",
    orientation: "landscape",
    environment: "ENGINEERING_LAB",
    priority: 1,
    alt: "Structural stress analysis of monocoque front triangle",
    caption: "FEA stress vector mapping across headtube junction",
  },
  carbonLayupDevelopment: {
    id: "carbon-layup-development",
    src: "/images/story/carbon-fiber-layup-development.png",
    category: "carbon",
    subjects: ["Carbon Fiber", "Layup", "Composite"],
    bikeFinish: "CARBON",
    orientation: "landscape",
    environment: "ENGINEERING_LAB",
    priority: 1,
    alt: "Precision manual carbon fiber ply orientation during layup",
    caption: "Unidirectional carbon ply layup orientation for torsional stiffness",
  },
  componentDevelopmentBench: {
    id: "component-development-bench",
    src: "/images/story/component-development-bench.png",
    category: "component",
    subjects: ["Components", "CNC", "Brakes"],
    bikeFinish: "NONE",
    orientation: "landscape",
    environment: "ENGINEERING_LAB",
    priority: 1,
    alt: "CNC machined aluminum linkages and titanium hardware on bench",
    caption: "5-axis CNC machined AL7075-T6 linkage hardware",
  },
  workshopChassisAssembly: {
    id: "workshop-chassis-assembly",
    src: "/images/story/workshop-chassis-assembly.png",
    category: "workshop",
    subjects: ["Assembly", "Build", "Workshop"],
    bikeFinish: "GLACIER",
    orientation: "landscape",
    environment: "ENGINEERING_LAB",
    priority: 1,
    alt: "Precision torque assembly of Project 01 prototype chassis",
    caption: "Precision chassis assembly using calibrated digital torque tools",
  },
  standaloneWhiteBike: {
    id: "standalone-white-bike",
    src: "/images/story/standalone-white-bike-presentation.png",
    category: "product",
    subjects: ["Project 01", "Glacier White"],
    bikeFinish: "GLACIER",
    orientation: "landscape",
    environment: "ALPINE_PRECISION",
    priority: 1,
    alt: "ALKOTA Project 01 Glacier White full presentation",
    caption: "Project 01 — Glacier White Alpine Precision finish",
  },
  standaloneBlackBike: {
    id: "standalone-black-bike",
    src: "/images/story/standalone-black-bike-presentation.png",
    category: "product",
    subjects: ["Project 01", "Naked Carbon"],
    bikeFinish: "CARBON",
    orientation: "landscape",
    environment: "ENGINEERING_LAB",
    priority: 1,
    alt: "ALKOTA Project 01 Naked Carbon full presentation",
    caption: "Project 01 — Naked Carbon raw composite finish",
  },
  technicalCadMaterial: {
    id: "technical-cad-material",
    src: "/images/story/technical-cad-engineering-material.png",
    category: "engineering",
    subjects: ["CAD", "Blueprint"],
    bikeFinish: "NONE",
    orientation: "landscape",
    environment: "ENGINEERING_LAB",
    priority: 2,
    alt: "3D CAD assembly blueprint of rear suspension linkage",
    caption: "Linkage geometry blueprint and bearing load paths",
  },
  frameDevelopmentMould: {
    id: "frame-development-mould",
    src: "/images/story/frame-development-mould-tooling.png",
    category: "carbon",
    subjects: ["Mould", "Tooling", "Manufacturing"],
    bikeFinish: "NONE",
    orientation: "landscape",
    environment: "ENGINEERING_LAB",
    priority: 2,
    alt: "CNC steel mould tooling for carbon fiber monocoque front triangle",
    caption: "Internal bladder compaction mould tooling",
  },
  reverseEngineeringTelemetry: {
    id: "reverse-engineering-telemetry",
    src: "/images/story/reverse-engineering-telemetry.png",
    category: "testing",
    subjects: ["Telemetry", "Reverse Engineering"],
    bikeFinish: "PROTOTYPE",
    orientation: "landscape",
    environment: "ENGINEERING_LAB",
    priority: 1,
    alt: "Shock velocity and wheel displacement telemetry trace analysis",
    caption: "High-frequency wheel displacement telemetry logging",
  },
  kinematicDynamicsAnalysis: {
    id: "kinematic-dynamics-analysis",
    src: "/images/story/kinematic-dynamics-analysis.png",
    category: "design",
    subjects: ["Kinematics", "Dynamics"],
    bikeFinish: "NONE",
    orientation: "landscape",
    environment: "ENGINEERING_LAB",
    priority: 1,
    alt: "Virtual pivot movement and anti-squat kinematics chart",
    caption: "Pedal kickback and anti-rise kinematic optimization",
  },
  prototypeBuildValidation: {
    id: "prototype-build-validation",
    src: "/images/story/prototype-build-validation.png",
    category: "workshop",
    subjects: ["Prototype", "Validation"],
    bikeFinish: "PROTOTYPE",
    orientation: "landscape",
    environment: "ENGINEERING_LAB",
    priority: 1,
    alt: "Complete prototype bike on workshop workstand during setup",
    caption: "REV 001 prototype build validation pass",
  },
  completeMachineIntegration: {
    id: "complete-machine-integration",
    src: "/images/story/complete-machine-integration.png",
    category: "product",
    subjects: ["Complete Machine", "Integration"],
    bikeFinish: "GLACIER",
    orientation: "landscape",
    environment: "ALPINE_PRECISION",
    priority: 1,
    alt: "Side profile of fully integrated Project 01 mountain bike",
    caption: "The complete machine — integrated as one cohesive system",
  },
  hauteSavoieAlpineTest: {
    id: "haute-savoie-alpine-test",
    src: "/images/story/haute-savoie-alpine-field-test.png",
    category: "testing",
    subjects: ["Haute-Savoie", "Alpine", "Field Test"],
    bikeFinish: "GLACIER",
    orientation: "landscape",
    environment: "TERRAIN_HUMAN",
    priority: 1,
    alt: "Real terrain testing in Haute-Savoie alpine mountains at 2,400m",
    caption: "Field testing on Haute-Savoie alpine descents at 2,400m elevation",
  },
  laboratoryStressFatigue: {
    id: "laboratory-stress-fatigue",
    src: "/images/story/laboratory-stress-fatigue-bench.png",
    category: "testing",
    subjects: ["Laboratory", "Fatigue", "Stress Test"],
    bikeFinish: "CARBON",
    orientation: "landscape",
    environment: "ENGINEERING_LAB",
    priority: 1,
    alt: "Multi-axis pneumatic hydraulic stress rig testing frame headtube",
    caption: "ISO+ multi-axis hydraulic fatigue bench test target",
  },
  alpineTrailTestingAction: {
    id: "alpine-trail-testing-action",
    src: "/images/story/alpine-trail-testing-action.png",
    category: "alpine",
    subjects: ["Trail", "Action", "Riding"],
    bikeFinish: "GLACIER",
    orientation: "landscape",
    environment: "TERRAIN_HUMAN",
    priority: 1,
    alt: "High-speed rider cornering on loose rock alpine singletrack",
    caption: "Validating lateral chassis stiffness under heavy cornering loads",
  },
};
